### ISSUE TITLE
Custom TItleBar is clickable through

### ISSUE THREAD

**Issue by IcySnex** [castorix/WinUI3_Transparent#1]
When you try to create a custom TitleBar with ```ExtendsContentIntoTitleBar = true;``` & ```SetTitleBar(AppTitleBar);```. 
The part of the TitleBar is not clickable. 
Every mouse input you try to enter will not work and it will activate the window underneath it.

I know you have to resize the transparent rectangle but changing the ```FillRect(wParam, ref rect, hBrush);``` top value (```rect.top = 32;```) inside the ```SetWIndowSubClass``` function has no effect.

I know its possible since I have seen youve already created a sample for this on Windows 10 [(mentioned here)](https://github.com/microsoft/microsoft-ui-xaml/issues/6993#issuecomment-1107532065), but how did you do it?

**Comment by mcNets** [comment]
WinUI 3 gallery has an option that allows you to extend the TitleBar, and the corresponding source code.  Does it only work on packaged applications?

**Comment by castorix** [comment]
I had quickly tested with [ExcludeClipRect](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-excludecliprect) to exclude the part with the Title Bar (and a region otherwise some blank parts appear behind...)

**Comment by IcySnex** [comment]
@castorix
Using a region and exluding the titlebar region does not work either. The output is the same. I dont know if I am doing something wrong but Im doing it like you described above.
This is my code:
```
public static int WindowSubClass(IntPtr hWnd, uint uMsg, IntPtr wParam, IntPtr lParam, IntPtr uIdSubclass, uint dwRefData)
{
    switch (uMsg)
    {
        case WM_ERASEBKGND:
        {
            GetClientRect(hWnd, out RECT rect); // Get window client area

            IntPtr reg = CreateRectRgn(0, 0, rect.right, rect.bottom); // Create region based on client area
            ExcludeClipRect(reg, 0, 0, rect.right, 32); // Exclude titlebar area

            IntPtr hBrush = CreateSolidBrush(ColorTranslator.ToWin32(Color.Magenta)); // Create transparent color brush

            FillRgn(wParam, reg, hBrush); // Fill client area with color

            DeleteObject(hBrush); // Delete brush
            return 1;
        }
    }
    return DefSubclassProc(hWnd, uMsg, wParam, lParam);
}
```
I would really appreciate it if you could upload your code which you used, thanks for taking time to respond.

**Comment by castorix** [comment]
I had deleted my test with the region (I think I called CreateRoundRectRgn if I used a rounded border)
But without region to remove the blank part, if I test with ExcludeClipRect (first parameter is the HDC...) , I can use the caption normally : (it needs more code if the window is resized (like maximized/restored))

           
```
                    case WM_ERASEBKGND:
                    { 
                        RECT rect;
                        GetClientRect(hWnd, out rect);
                        int nRet = ExcludeClipRect(wParam, 0, 0, rect.right, 35);
                        IntPtr hBrush = CreateSolidBrush(System.Drawing.ColorTranslator.ToWin32(System.Drawing.Color.Magenta));
                        FillRect(wParam, ref rect, hBrush);
                        DeleteObject(hBrush);
                        return 1;
                    }
                    break;
```

**Comment by IcySnex** [comment]
This has the same output if you just set ```rect.top = 32;``` after calling ```GetClientRect(...);```.
You said "it needs more code if the window is resized (maximize/restore)": This is the problem Im currently facing.
It does some weird visual artifacts when restoring from the maximized window and no matter what code I am adding, they dont dissapear?

**Comment by castorix** [comment]
It is difficult to manage; it is a 3rd window ("DRAG_BAR_WINDOW_CLASS") added to main window and XAML window, layered with WS_EX_NOREDIRECTIONBITMAP
For custom windows, it is easier without caption.
